# Generated by Django 3.1.7 on 2021-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kuberapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Complete', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
